# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "9.2.0"

    steps:
      - checkout
      
      - run:
          name: Before Install
          command: |
            sudo systemsetup -settimezone Europe/Tallinn
            export LC_ALL=en_US.UTF-8
            export LANG=en_US.UTF-8
            echo -e "machine bitbucket.org\n  login fassko\n  password $CI_USER_PASSWORD" >> ~/.netrc 
          
      - run:
          name: Cocoapods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            pod install --repo-update
          
      - run:
          name: Install
          command: |
            sudo gem install fastlane --no-doc
            sudo gem cleanup

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: fastlane circleci
