name: Build and test Weather Latvia

on: push

env:
  DEVELOPER_DIR: /Applications/Xcode_11.6.app/Contents/Developer

jobs:
  build:
    name: Build and test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Install Swiftlint
      run: brew install swiftlint
      
    - name: Run tests
      run: set -o pipefail && xcodebuild -project MeteoLV.xcodeproj -scheme MeteoLV -destination 'platform=iOS Simulator,name=iPhone 11 Pro' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean test build | xcpretty
