update_fastlane

default_platform(:ios)

platform :ios do
  desc "Certs"
  lane :certificates do
    match(type: "appstore")
    match(type: "development")
  end

  lane :generate_icon do
    appicon(appicon_image_file: 'Icon.png',
      appicon_devices: [:ipad, :iphone, :ios_marketing],
      appicon_path: 'MeteoLV/Assets.xcassets'
    )
  end

  desc "UI tests"
  lane :test do
    # Test
    scan(
      workspace: "MeteoLV.xcworkspace",
			scheme: "MeteoLV",
			clean: true,
      device: "iPhone X",
      xcargs: "CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED=NO",
      configuration: "Debug"
    )
  end

  lane :build do
    increment_build_number build_number: get_version_number + "." + Time.new.strftime("%y%m%d.%H%M")

    clear_derived_data

    gym(
      workspace: "MeteoLV.xcworkspace",
      scheme: "MeteoLV",
      clean: true,
      output_name: "MeteoLV.ipa",
      include_symbols: true
    )
  end

  lane :beta do
    build
    testflight(
      skip_waiting_for_build_processing: true
    )
  end

  lane :screenshots do
    snapshot
  end

  lane :release do
    build
    upload_to_app_store
  end

  desc "Deploy a new version to the App Store"
  lane :release_github do
    ensure_git_branch
    version = get_version_number
    changelog = changelog_from_git_commits(merge_commit_filtering: "exclude_merges")

    github_release = set_github_release(
      repository_name: "fassko/MeteoLV",
      api_token: ENV['GITHUB_TOKEN'],
      name: version,
      tag_name: version,
      description: changelog,
      commitish: "master"
    )
    sh("git fetch --tags")
  end

  desc "Download dSYMs and upload to Testflight"
  lane :dsyms do
    download_dsyms(
      platform: "ios"
    )
    upload_symbols_to_crashlytics(
      api_token: "e8586ed0363ddcd4fc38b8f3aff4d3e095de5f07"
    )
    clean_build_artifacts
  end
end
