devices([
  "iPhone SE",
  "iPhone 5s",
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone X"
])

languages([
  "en-US"
])

scheme("MeteoLV")

output_directory("./screenshots")

clear_previous_screenshots(true)

workspace "./MeteoLV.xcworkspace"
